# Generated by Django 4.0.6 on 2022-08-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_availiable', models.BooleanField(default=False)),
                ('premiere_date', models.DateField()),
            ],
        ),
    ]
